app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::bind('product', function($slug){
	return App\Product::where('slug', $slug)->first();
});

// Category dependency injection
Route::bind('category', function($category){
    return App\Category::find($category);
});

// User dependency injection
Route::bind('user', function($user){
    return App\User::find($user);
});


Route::get('/', [
	'as' => 'home',
	'uses' => 'StoreController@index'
]);

Route::get('product/{slug}', [
	'as' => 'product-detail',
	'uses' => 'StoreController@show'
]);
Route::get('store/partials/{category_id}', [
	'as' => 'products-cate',
	'uses' => 'StoreController@seccion'
]);
Route::get('store/partials', [
	'as' => 'seccione',
	'uses' => 'StoreController@seccione'
]);
// Carrito -------------

Route::get('cart/show', [
	'as' => 'cart-show',
	'uses' => 'CartController@show'
]);

Route::get('cart/add/{product}', [
	'as' => 'cart-add',
	'uses' => 'CartController@add'
]);

Route::get('cart/delete/{product}',[
	'as' => 'cart-delete',
	'uses' => 'CartController@delete'
]);

Route::get('cart/trash', [
	'as' => 'cart-trash',
	'uses' => 'CartController@trash'
]);

Route::get('cart/update/{product}/{quantity}', [
	'as' => 'cart-update',
	'uses' => 'CartController@update'
]);

Route::get('order-detail', [
	'middleware' => 'auth:user',
	'as' => 'order-detail',
	'uses' => 'CartController@orderDetail'
]);
Route::get('store/partials/hogar', [
	'as' => 'seccion',
	'uses' => 'StoreController@seccion'
]);

// Authentication routes...
Route::get('auth/login', [
	'as' => 'login-get',
	'uses' => 'Auth\AuthController@getLogin'
]);

Route::post('auth/login', [
	'as' => 'login-post',
	'uses' => 'Auth\AuthController@postLogin'
]);

Route::get('auth/logout', [
	'as' => 'logout',
	'uses' => 'Auth\AuthController@getLogout'
]);

// Registration routes...
Route::get('auth/register', [
	'as' => 'register-get',
	'uses' => 'Auth\AuthController@getRegister'
]);

Route::post('auth/register', [
	'as' => 'register-post',
	'uses' => 'Auth\AuthController@postRegister'
]);

// Paypal

// Enviamos nuestro pedido a PayPal
Route::get('payment', array(
	'as' => 'payment',
	'uses' => 'PaypalController@postPayment',
));

// Después de realizar el pago Paypal redirecciona a esta ruta
Route::get('payment/status', array(
	'as' => 'payment.status',
	'uses' => 'PaypalController@getPaymentStatus',
));


// ADMIN -------------

Route::group(['namespace' => 'Admin', 'middleware' => ['auth'], 'prefix' => 'admin'], function()
{

	Route::get('home', function(){
		return view('admin.home');
	});

	Route::resource('category', 'CategoryController');

	Route::resource('product', 'ProductController');
	Route::post('store', 'Admin\ProductController@store');

	Route::resource('user', 'UserController');

	Route::get('orders', [
		'as' => 'admin.order.index',
		'uses' => 'OrderController@index'
	]);

	Route::post('order/get-items', [
	    'as' => 'admin.order.getItems',
	    'uses' => 'OrderController@getItems'
	]);

	Route::get('order/{id}', [
	    'as' => 'admin.order.destroy',
	    'uses' => 'OrderController@destroy'
	]);

});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = 'products';

	protected $fillable = ['name', 'slug', 'description', 'extract', 'image', 'visible', 'price', 'category_id'];

    
    // Relation with Category
    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    // Relation with OrderItem
    public function order_item()
    {
        return $this->hasOne('App\OrderItem');
    }
     public function scopeName($query,$name)
     {

            if(trim($name) != ""){ 
            $query->where(\DB::raw("CONCAT(extract, ' ', description)"),"LIKE", '%'.$name.'%')
            ->orwhere(\DB::raw("CONCAT(name, ' ', extract)"),"LIKE", '%'.$name.'%')
            ->orwhere(\DB::raw("CONCAT(description, ' ', extract)"),"LIKE", '%'.$name.'%');
            


             }
             }    

}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\SaveProductRequest;
use App\Http\Controllers\Controller;
use Storage;
use Illuminate\Http\JsonResponse;

use App\Product;
use App\Category;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $products = Product::orderBy('id', 'desc')->paginate(5);
        //dd($products);
        return view('admin.product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $categories = Category::all();
        //dd($categories);
        return view('admin.product.create')->with('categories',$categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(SaveProductRequest $request)
    {

            $ima = $request->file('file');

                          $producto= new Product; 
             $producto->name= $request->input("name");
             $producto->slug= str_slug($request->input('name'));
             $producto->description= $request->input("description");
             $producto->extract= $request->input("extract");
             $producto->price= $request->input("price");
             $producto->visible= $request->has('visible') ? 1 : 0;
             $producto->category_id= $request->input("category_id");

           $carpeta=$request->input("category_id");
           $im=$carpeta."/".$request->input("visible")."_".$ima->getClientOriginalName();
           $r1=Storage::disk('fotografias')->put($im,  \File::get($ima) );
           $rutai="storage/fotografias/".$im;
           $producto->image=$rutai;
             $producto->save();

        $message = $producto ? 'Producto agregado correctamente!' : 'El producto NO pudo agregarse!';
        
        return redirect()->route('admin.product.index')->with('message', $message);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show(Product $product)
    {
        return $product;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit(product $product)
    {

        //dd($categories);
        return view('admin.product.edit')->with('product',$product);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(SaveProductRequest $request, Product $product)
    {
                    $ima = $request->file('file');
   $data=$request->all();
        
        $idUsuario=$data["id_pro"];
             $producto= Product::find($idUsuario);
             $producto->name= $request->input("name");
             $producto->slug= str_slug($request->input('name'));
             $producto->description= $request->input("description");
             $producto->extract= $request->input("extract");
             $producto->price= $request->input("price");
             $producto->visible= $request->has('visible') ? 1 : 0;
             $producto->category_id= $request->input("category_id");

                   $carpeta=$request->input("category_id");
           $im=$carpeta."/".$request->input("visible")."_".$ima->getClientOriginalName();
           $r1=Storage::disk('fotografias')->put($im,  \File::get($ima) );
           $rutai="storage/fotografias/".$im;
           $producto->image=$rutai;

        $updated = $producto->save();
        
        $message = $updated ? 'Producto actualizado correctamente!' : 'El Producto NO pudo actualizarse!';
        
        return redirect()->route('admin.product.index')->with('message', $message);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy(Product $product)
    {
        $deleted = $product->delete();
        
        $message = $deleted ? 'Producto eliminado correctamente!' : 'El producto NO pudo eliminarse!';
        
        return redirect()->route('admin.product.index')->with('message', $message);
    }
}

resources/views/admin/product/create.blade.php
@extends('admin.template')

@section('content')
    
    <div class="container text-center">
        <div class="page-header">
            <h1>
                <i class="fa fa-shopping-cart"></i>
                PRODUCTOS <small>[Agregar producto]</small>
            </h1>
        </div>

        <div class="row">
            <div class="col-md-offset-3 col-md-6">
                    @if (count($errors) > 0)
                        @include('admin.partials.errors')
                    @endif
                <div class="page">

<form  method="POST"  action="{{ route('admin.product.store') }}" class="formarchivo"   enctype="multipart/form-data">

                 <input type="hidden" name="_token" value="<?php echo csrf_token(); ?>"> 
                                                      <div class="form-group">
                            <label class="control-label" for="category_id">Categoría</label>
<select  name="category_id" class="form-control" id="category_id">
@foreach ($categories as $categorie)
    <option value="{{ $categorie->id }}">{{$categorie->name}}</option>
@endforeach
</select>
                        </div>
        
                        <div class="form-group">
                            <label for="name">Nombre:</label>
                            <input type="text" name="name" class="form-control" autofocus="autofocus" placeholder="Ingresa el nombre">
                        </div>
                        
                        <div class="form-group">
                            <label for="extract">Extracto:</label>
                                            <input type="text" name="extract" id="extract" class="form-control" placeholder="Ingresa el extracto">
                        </div>
                        
                        <div class="form-group">
                            <label for="description">Descripción:</label>
    <textarea type="text" name="description" id="description" class="form-control" placeholder="Ingresa la description"></textarea>
                        </div>
                        
                        <div class="form-group">
                            <label for="price">Precio:</label>
                            <input type="text" name="price" id="price" class="form-control" placeholder="Ingresa el precio">
                        </div>
                        
                        <div class="form-group">
                            <label for="image">Imagen:</label>
                            
<input type="file" name="file" id="file">
                        </div>
                        
                        <div class="form-group">
                            <label for="visible">Visible:</label>
                                
                            <input type="checkbox" name="visible">
                        </div>
                        
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Guardar</button>
                            <a href="{{ route('admin.product.index') }}" class="btn btn-warning">Cancelar</a>
                        </div>
                    </form>                    
                </div>
                
            </div>
        </div>
        

    </div>

@stop

resources/views/admin/product/edit.blade.php
@extends('admin.template')

@section('content')
	
	<div class="container text-center">
		<div class="page-header">
			<h1>
				<i class="fa fa-shopping-cart"></i>
				PRODUCTOS <small>[Editar producto]</small>
			</h1>
		</div>

		<div class="row">
            <div class="col-md-offset-3 col-md-6">
                
                <div class="page">
                    
                    @if (count($errors) > 0)
                        @include('admin.partials.errors')
                    @endif
                    
                    <form  method="POST"  action="{{ route('admin.product.update') }}" class="formarchivo"   enctype="multipart/form-data">

                        <input type="hidden" name="_method" value="PUT">
                                     <input type="hidden" name="id_pro" value="<?= $product->id; ?>"> 

                 <input type="hidden" name="_token" value="<?php echo csrf_token(); ?>"> 
                                                      <div class="form-group">
                            <label class="control-label" for="category_id">Categoría</label>
<select  name="category_id" class="form-control" id="category_id">
    <option value="{{ $product->category_id }}">{{$product->category->name}}</option>
</select>
                        </div>
        
        
                        <div class="form-group">
                            <label for="name">Nombre:</label>
                            <input type="text" name="name" class="form-control" autofocus="autofocus" placeholder="Ingresa el nombre" value="{{$product->name}}">
                        </div>
                        
                        <div class="form-group">
                            <label for="extract">Extracto:</label>
                                            <input type="text" name="extract" id="extract" class="form-control" placeholder="Ingresa el extracto" value="{{$product->extract}}">
                        </div>
                        
                        <div class="form-group">
                            <label for="description">Descripción:</label>
<textarea type="text" name="description" id="description" class="form-control" placeholder="Ingresa la description">{{$product->description}}</textarea>
                        </div>
                        
                        <div class="form-group">
                            <label for="price">Precio:</label>
                            <input type="text" name="price" id="price" class="form-control" placeholder="Ingresa el precio" value="{{$product->price}}">
                        </div>
                        
                        <div class="form-group">
                            <label for="image">Imagen:</label>
                            
<input type="file" name="file" id="file">
                        </div>
                        
                        <div class="form-group">
                            <label for="visible">Visible:</label>
                            <input type="checkbox" name="visible" {{ $product->visible == 1 ? "checked='checked'" : '' }}>
                        </div>
                
                        
                        
                        
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Guardar</button>
                            <a href="{{ route('admin.product.index') }}" class="btn btn-warning">Cancelar</a>
                        </div>
                    
</form>                    
                </div>
                
            </div>
        </div>
        

	</div>

@stop

resources/views/admin/product/index.blade.php
@extends('admin.template')

@section('content')

	<div class="container text-center">
		<div class="page-header">
			<h1>
				<i class="fa fa-shopping-cart"></i>
				PRODUCTOS 
				<a href="{{ route('admin.product.create') }}" class="btn btn-warning">
					<i class="fa fa-plus-circle"></i> Producto
				</a>
			</h1>
		</div>
		<div class="page">
            
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>Editar</th>
                            <th>Eliminar</th>
                            <th>Imagen</th>
                            <th>Nombre</th>
                            <th>Categoría</th>
                            <th>Extracto</th>
                            <th>Precio</th>
                            <th>Visible</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($products as $product)
                            <tr>
                                <td>
                                    <a href="{{ route('admin.product.edit', $product->slug) }}" class="btn btn-primary">
                                        <i class="fa fa-pencil-square-o"></i>
                                    </a>
                                </td>
                                <td>
                                    {!! Form::open(['route' => ['admin.product.destroy', $product->slug]]) !!}
        								<input type="hidden" name="_method" value="DELETE">
        								<button onClick="return confirm('Eliminar registro?')" class="btn btn-danger">
        									<i class="fa fa-trash-o"></i>
        								</button>
        							{!! Form::close() !!}
                                </td>
                                <td><img src="{{ url($product->image) }}" width="40"></td>
                                <td>{{ $product->name }}</td>
                                <td>{{ $product->category->name }}</td>
                                <td>{{ $product->extract }}</td>
                                <td>${{ number_format($product->price,2) }}</td>
                                <td>{{ $product->visible == 1 ? "Si" : "No" }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            
            <hr>
            
            <?php echo $products->render(); ?>
            
        </div>

	</div>
	
@stop